service:
  - mysql
install:
  - "npm install"
  - "export TRAVIS=1"
before_script:
    - mysql -e 'create database test;'
    - mysql -e 'create database test2;'
language: node_js
node_js:
  - "5.0.0"
